- hosts: dce
  tasks:
  #- name: upgrade shell
   # shell: "docker run --rm daocloud.io/daocloud/dce:2.10.3-dev upgrade --force-pull| sed 's/-it/-t/g' > /var/tmp/upgrade_cluster.sh"
  #- name: upgrade
   # shell: bash /var/tmp/upgrade_cluster.sh

- hosts: localhost
  tasks:
  - name: create result directory
    file: path=/var/jenkins_home/result state=directory

- hosts: ansiblehost
  tasks:
  - name: copy test case
    copy: src=host_healthy.robot dest=/var/jenkins_home/host_healthy.robot
  - name: copy test case
    copy: src=host_healthy.robot dest=/var/jenkins_home/appadd.robot
  - name: copy test case
    copy: src=host_healthy.robot dest=/var/jenkins_home/appdelete.robot
  - name: create result directory
    file: path=/var/jenkins_home/result state=directory
  - name: exec
    shell: robot --outputdir  /var/jenkins_home/result /var/jenkins_home/host_healthy.robot
  - name: exec
    shell: robot --outputdir  /var/jenkins_home/result /var/jenkins_home/appadd.robot
  - name: exec
    shell: robot --outputdir  /var/jenkins_home/result /var/jenkins_home/appdelete.robot
  - name: fetch result
    fetch: src=/var/jenkins_home/result/output.xml dest=/var/jenkins_home/workspace/robot-framework flat=yes
  - name: fetch result
    fetch: src=/var/jenkins_home/result/report.html dest=/var/jenkins_home/workspace/robot-framework flat=yes
  - name: fetch result
    fetch: src=/var/jenkins_home/result/log.html dest=/var/jenkins_home/workspace/robot-framework flat=yes
